import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame,isHuman,nextRound,rollDice,placeDice,miniAction,validSave,outcome} from '../dist/core.mjs';
function setup(kind){const g=createGame(4,()=>.1,{rules:'classic',hero:2});g.tables[0].effect=kind;rollDice(g,()=>0);placeDice(g,1,()=>0);return g;}
test('all four selectable heroes own first turn; two humans wrap clockwise',()=>{for(let hero=0;hero<4;hero++){const g=createGame(2,Math.random,{hero});assert.equal(g.turn,hero);assert(isHuman(g,hero));assert(isHuman(g,(hero+1)%4));assert(!isHuman(g,(hero+2)%4));nextRound(g);assert.equal(g.turn,(hero+1)%4);}});
test('second place takes large note; sole survivor only takes small note',()=>{const t={effect:'reverse',notes:[90000,20000],counts:[3,2,0,0]};assert.deepEqual(outcome(t).awards,[{player:0,amount:20000},{player:1,amount:90000}]);t.counts=[3,0,0,0];assert.deepEqual(outcome(t).unused,[90000]);});
test('21-point success, bust, bank and pending save restore',()=>{let g=setup('blackjack');assert.equal(g.phase,'minigame');assert.equal(g.players[2].left,0);assert(validSave(g));miniAction(g,'draw',()=>.99);assert.equal(g.pending.total,18);miniAction(g,'bank');assert.equal(g.tables[0].bonus[2],1);assert(validSave(JSON.parse(JSON.stringify(g))));miniAction(g,'continue');assert.equal(g.turn,3);assert.equal(g.phase,'ready');g=setup('blackjack');miniAction(g,'draw',()=>.99);miniAction(g,'draw',()=>.99);assert.equal(g.pending.earned,0);g=setup('blackjack');miniAction(g,'draw',()=>.99);miniAction(g,'draw',()=>.4);assert.equal(g.pending.total,21);assert.equal(g.pending.earned,2);});
test('high-low equal loses; pressing can lose earned first win',()=>{const g=setup('highlow');miniAction(g,'higher',()=>.7);assert.equal(g.pending.wins,1);miniAction(g,'lower',()=>.7);assert.equal(g.pending.stage,'done');assert.equal(g.pending.earned,0);const h=setup('highlow');miniAction(h,'higher',()=>.99);miniAction(h,'bank');assert.equal(h.tables[0].bonus[2],1);});
test('illegal mini actions preserve state and bonus participates in ties',()=>{const g=setup('blackjack'),before=JSON.stringify(g);assert(!miniAction(g,'higher'));assert(!miniAction(g,'continue'));assert.equal(JSON.stringify(g),before);assert.deepEqual(outcome({effect:'blackjack',counts:[2,3,1,0],bonus:[1,0,0,0],notes:[90000,20000]}).ties,[0,1]);});
test('last physical die waits for mini completion before settlement',()=>{const g=createGame(4,Math.random,{rules:'classic'});for(let i=0;i<3;i++){rollDice(g,()=>0);placeDice(g,1);}g.tables[1].effect='highlow';rollDice(g,()=>.2);placeDice(g,2,()=>0);assert.equal(g.phase,'minigame');miniAction(g,'bank');assert.equal(g.phase,'minigame');miniAction(g,'continue');assert.equal(g.phase,'settled');assert(validSave(g));});
test('same player triggers a mini only on first investment that round',()=>{const g=createGame(4,Math.random,{rules:'classic'});g.tables[0].effect='blackjack';rollDice(g,()=>0);g.roll=[1,2,2,2,2,2,2,2];placeDice(g,1);miniAction(g,'bank');miniAction(g,'continue');for(let i=0;i<3;i++){rollDice(g,()=>.2);placeDice(g,2);}rollDice(g,()=>0);placeDice(g,1);assert.notEqual(g.phase,'minigame');});
