async(parent)=>{const reports=[];for(const width of [1440,390]){const ctx=await parent.context().browser().newContext({viewport:{width,height:960}}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));try{
 await p.addInitScript(()=>{if(!localStorage.getItem('vegas-night-prefs-v2'))localStorage.setItem('vegas-night-prefs-v2',JSON.stringify({sound:false,music:true,musicVolume:.28,fast:true,motion:true,cutins:true}));const Native=window.AudioContext;window.AudioContext=class extends Native{createMediaElementSource(element){const node=super.createMediaElementSource(element),connect=node.connect.bind(node);node.connect=(dest,...args)=>{if(element.id==='game-music')window.__bgmGain=dest;return connect(dest,...args);};return node;}};});
 await p.goto('http://127.0.0.1:4317');if(await p.locator('#game-music').getAttribute('src'))throw Error('Autoplay before gesture');
 const playing=async track=>p.waitForFunction(t=>{const a=document.getElementById('game-music');return a.dataset.track===t&&!a.paused&&a.currentTime>.1&&!a.error},track).catch(async e=>{throw Error('playing '+track+' '+JSON.stringify(await p.locator('#game-music').evaluate(a=>({src:a.src,paused:a.paused,time:a.currentTime,error:a.error?.message,track:a.dataset.track}))))});
 const time=()=>p.locator('#game-music').evaluate(a=>a.currentTime);
 await p.locator('[data-action="lobby-settings"]').click();await playing('lobby');await p.locator('[data-pref="musicVolume"]').fill('46');await p.waitForFunction(()=>Math.abs(window.__bgmGain.gain.value-.46)<.025).catch(()=>{throw Error('Volume gain timeout')});await p.screenshot({path:'output/playwright/v12-music-settings-'+width+'.png'});
 await p.locator('[data-pref="music"]').uncheck();await p.waitForFunction(()=>document.getElementById('game-music').paused);const stopped=await time();await p.locator('[data-pref="music"]').check();await playing('lobby');if(await time()<stopped-.15)throw Error('Mute reset playback');
 await p.locator('[data-action="credits"]').click();if(await p.locator('#modal a[href*="silvermansound.com/free-music/"]').count()!==3)throw Error('Credits missing');await p.locator('#modal [data-action="close"]').click();await playing('lobby');const before=await time();await p.locator('.lobby-start').click();await p.locator('[data-hero-step="1"]').click();await p.waitForTimeout(350);if(await time()<before)throw Error('Selection restarted music');if(await p.locator('#game-music').getAttribute('data-track')!=='lobby')throw Error('Selection changed music');
 await p.locator('.setup-details summary').click();await p.locator('#mode').selectOption('4');await p.locator('[data-action="start"]').click();await p.locator('#modal [data-action="close"]').click();await playing('table');await p.locator('#app [data-action="pause"]').click();await p.waitForFunction(()=>document.getElementById('game-music').paused);const paused=await time();await p.locator('#modal [data-action="close"]').click();await playing('table');if(await time()<paused-.15)throw Error('Pause reset playback');
 await p.locator('#app [data-action="settings"]').click();await p.locator('[data-preview="1"]').click();await p.locator('#cinema[open]').waitFor();await p.waitForFunction(()=>window.__bgmGain.gain.value<.23).catch(()=>{throw Error('Ducking timeout')});await p.locator('#cinema .cinema-skip').click();await p.waitForFunction(()=>window.__bgmGain.gain.value>.42).catch(()=>{throw Error('Unduck timeout')});await p.locator('#modal [data-action="close"]').click();
 await p.locator('#app [data-action="tutorial"]').click();await playing('lobby');await p.locator('[data-basic="exit"]').click();await p.locator('#modal [data-action="exam"]').click();await playing('table');await p.locator('[data-exam="exit"]').click();
 await p.evaluate(async()=>{const core=await import('./core.mjs'),g=JSON.parse(localStorage.getItem('vegas-night-save-v5'));g.round=4;if(!core.validSave(g))throw Error('Invalid final fixture');});await p.addInitScript(()=>{const g=JSON.parse(localStorage.getItem('vegas-night-save-v5'));if(g){g.round=4;localStorage.setItem('vegas-night-save-v5',JSON.stringify(g));}});await p.reload();await p.locator('.lobby-continue').click();await playing('final');
 await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});await p.waitForFunction(()=>document.getElementById('game-music').paused);await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>false});document.dispatchEvent(new Event('visibilitychange'));});if(!await p.locator('#game-music').evaluate(a=>a.paused))throw Error('Music resumed behind pause dialog');await p.locator('#modal [data-action="close"]').click();await playing('final');
 const saved=await p.evaluate(()=>JSON.parse(localStorage.getItem('vegas-night-prefs-v2')));if(saved.sound!==false||saved.music!==true||saved.musicVolume!==.46)throw Error('Prefs wrong');await p.locator('#app [data-action="settings"]').click();await p.locator('[data-pref="music"]').uncheck();await p.reload();await p.locator('.lobby-start').click();await p.waitForTimeout(400);if(await p.locator('#game-music').getAttribute('src'))throw Error('Mute not persisted');if(errors.length)throw Error(errors.join(';'));reports.push({width,gesture:true,lobbyContinuity:true,volume:true,mute:true,ducking:true,teaching:true,exam:true,final:true,background:true,errors});
 }finally{await ctx.close();}}return reports;}
