import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame,rollDice,placeDice,useSkill,validSave,settle,outcome,skipTurn} from '../dist/core.mjs';
import {activateRoyal,royalAction,royalOptions,royalActor,startPower,royalRefresh,royalReward} from '../dist/royale.mjs';
const game=id=>createGame(4,Math.random,{seed:102,hero:0,skills:true,balance:2,bigDice:true,modulePool:'royal',practice:id});
function enter(g){rollDice(g);return placeDice(g,1);}
test('lucky punch uses secret count versus next player and resolves guess without spending chips',()=>{const g=game('lucky');enter(g);const chips=g.players[0].chips;assert.ok(royalAction(g,'n1'));assert.equal(royalActor(g),1);assert.ok(royalAction(g,'n2'));assert.equal(g.players[0].chips,chips+2);assert.ok(validSave(g));});
test('no-entry blocks placement and cowboy removal; forced closed-only roll can wait with zero chips',()=>{const g=game('noentry');enter(g);royalAction(g,'seal6');royalAction(g,'continue');rollDice(g);g.roll.fill(6);g.players[g.turn].chips=0;const before=JSON.stringify(g);assert.equal(placeDice(g,6),false);assert.equal(JSON.stringify(g),before);assert.ok(skipTurn(g));assert.ok(validSave(g));g.tables[5].counts[2]++;g.players[2].left--;assert.equal(useSkill(g,1,{target:2,face:6,zone:'table'}),false);});
test('knockout stores physical big die, excludes it from table scores, and returns it on owner entry',()=>{const g=game('knockout');enter(g);assert.ok(royalAction(g,'bar1'));while(g.royale.pending.stage!=='done')royalAction(g,royalOptions(g)[0].id);assert.equal(g.royale.held.filter(d=>d.owner===1&&d.big).length,1);assert.equal(g.players[1].bigLeft,0);royalAction(g,'continue');assert.equal(g.turn,1);rollDice(g);g.roll[0]=1;placeDice(g,1);while(g.royale.pending.stage!=='done')royalAction(g,royalOptions(g)[0].id);assert.equal(g.players[1].bigLeft,1);assert.equal(g.royale.held.filter(d=>d.owner===1).length,0);assert.ok(validSave(g));});
test('neutral dice take a prize without promoting the next player and participate in ties',()=>{const t={counts:[2,1,0,0],big:[0,0,0,0],notes:[90000,40000],neutral:3};let o=outcome(t);assert.deepEqual(o.awards,[{player:0,amount:40000}]);assert.deepEqual(o.unused,[90000]);t.neutral=2;o=outcome(t);assert.deepEqual(o.ties,[0]);assert.deepEqual(o.awards,[{player:1,amount:90000}]);});
test('double-down dice remain protected from a cowboy and carry their big-die weight',()=>{const g=game('double');enter(g);const p=g.royale.pending,large=g.tables[0].big[0],small=g.tables[0].counts[0]-large;assert.ok(royalAction(g,`double-${small}-${large}`));assert.equal(g.tables[0].counts[0],0);assert.equal(g.royale.held.filter(d=>d.big).length,1);royalAction(g,'continue');assert.equal(useSkill(g,1,{target:0,zone:'table',face:1,big:true}),false);assert.ok(validSave(g));});
test('nice dice displaces the previous slot into its corresponding casino without reactivation',()=>{const g=game('nice');enter(g);royalAction(g,'nice-table-0');royalAction(g,'continue');rollDice(g);g.roll[0]=1;placeDice(g,1);const count=g.tables[0].counts[0],activations=g.tables[0].royal.activations;royalAction(g,'nice-table-0');assert.equal(g.tables[0].counts[0],count+1);assert.equal(g.tables[0].royal.activations,activations);assert.equal(g.royale.held.find(d=>d.kind==='nice').owner,1);assert.ok(validSave(g));});
test('power token substitutes exactly one set die for a normal roll and opens the destination module',()=>{const g=game('power');enter(g);assert.equal(g.tables[0].royal.holder,0);royalAction(g,'continue');g.turn=0;const left=g.players[0].left;assert.ok(startPower(g));assert.ok(royalAction(g,'power-6-0'));assert.equal(g.players[0].left,left-1);assert.equal(g.tables[5].counts[0],1);assert.ok(validSave(g));});
test('black box has six exact rewards, accepts a private split and pays only selected pile',()=>{const g=game('blackbox');for(const p of g.players){p.used=true;p.left=0;}for(let i=0;i<4;i++){g.tables[i].counts[i]=g.players[i].supply;g.tables[i].big[i]=1;g.players[i].bigLeft=0;}g.phase='ready';settle(g);assert.equal(g.royale.pending.kind,'blackpay');assert.equal(royalActor(g),1);royalAction(g,'split1');assert.equal(royalActor(g),0);const before=g.players[0].cash;royalAction(g,'left');assert.equal(g.players[0].cash-before,60000);assert.ok(validSave(g));});
test('illegal choices do not alter pending state or random counters',()=>{for(const id of ['lucky','fifty','nice','choice','handicap']){const g=game(id);enter(g);const before=JSON.stringify(g);assert.equal(royalAction(g,'invented-option'),false);assert.equal(JSON.stringify(g),before);assert.ok(validSave(g));}});
